import type { Metadata } from "next";
import { Rye } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar/Navbar";

const rye = Rye({
    weight: "400",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${rye.className} antialiased`}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
